services:
  - type: web
    name: zensignals-bot
    env: python
    buildCommand: pip install -r webapp/requirements.txt
    startCommand: gunicorn webapp.app:app
    envVars:
      - key: PORT
        value: 10000
